name: CI

on: [push, pull_request]

jobs:
  macos_intel_operational_test:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v2
    - run: brew install ./piping-server.rb
    - run: piping-server --version
    - run: piping-server --help

  linux_amd64_operational_test:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: brew install ./piping-server.rb
    - run: piping-server --version
    - run: piping-server --help
  
  linux_arm64_operational_test:
    # ERROR: "Homebrew on Linux is only supported on Intel processors!"
    if: false
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Operational test
      run: |
        docker run --rm -i -v $PWD:/ws --platform=linux/arm64/v8 ubuntu:18.04 bash <<'EOF'
        set -xeu
        cd /ws
        apt update && apt install -y curl git ruby
        # Install brew
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        brew install ./piping-server.rb
        piping-server --version
        piping-server --help
        EOF
